### ISSUE TITLE
nvims

### ISSUE THREAD

**Issue by 4Gettt25** [Traap/dotfiles#1]
when trying to execute nvims from terminal it starts and I am able to select the configs, BUT there also  appear errors.
the errors are as follows:
line 199:  /nvim_appnames: permission denied
line 200:  /nvim_appnames: permission denied
line 203:  /nvim_appnames: permission denied
line 203:  /nvim_appnames: permission denied
line 203:  /nvim_appnames: permission denied
line 203:  /nvim_appnames: permission denied
line 203:  /nvim_appnames: permission denied
line 203:  /nvim_appnames: permission denied
line 203:  /nvim_appnames: permission denied
line 203:  /nvim_appnames: permission denied
line 203:  /nvim_appnames: permission denied
line 203:  /nvim_appnames: permission denied

**Comment by 4Gettt25** [comment]
ok got it to work. So basically I had to reinstall neovim from source and then everything worked when I set the alias as sudo ./nvim_apps.sh

**Comment by Traap** [comment]
Thank you for the feedback.  I'll add a note to the script to advise others.
